import { test, expect } from '@playwright/test'

test('isolates editions and completes a manual Valorant tournament on mobile', async ({ page }) => {
  test.setTimeout(180_000)
  await page.goto('/admin/login')
  await page.getByPlaceholder('Contraseña').fill('e2e-admin-password')
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page).toHaveURL(/\/admin\?tournament=legacy-lol&game=lol$/)
  const request = page.request
  expect((await request.get('/api/admin/equipos')).status()).toBe(400)
  const editions = []
  for (const [index, game] of ['lol', 'lol', 'valorant'].entries()) {
    const res = await request.post('/api/admin/torneos', { data: { name: `Edition ${index}`, slug: `edition-${index}-${Date.now()}`, game, platform: 'pc', region: 'eu', status: 'draft' } })
    expect(res.ok()).toBeTruthy()
    editions.push(await res.json())
  }
  const val = editions[2]
  const scope = `?tournament=${val.id}&game=valorant`
  const teams = []
  for (const tournament of editions) {
    const res = await request.post(`/api/admin/equipos?tournament=${tournament.id}`, { data: { name: 'Repeated team name', players: [{ id: `player-${tournament.id}`, summonerName: 'Same#EUW', primaryRole: tournament.game === 'lol' ? 'Mid' : 'Flexible', rosterStatus: 'starter' }] } })
    expect(res.ok()).toBeTruthy()
    teams.push(await res.json())
  }
  const own = teams[2]
  expect((await request.get(`/api/data/equipos${scope}`)).status()).toBe(404)
  expect((await request.get(`/equipos/${own.id}`)).status()).toBe(404)
  const other = await request.post(`/api/admin/equipos${scope}`, { data: { name: 'Opponent', players: [] } })
  const opponent = await other.json()
  const phaseRes = await request.post(`/api/admin/fases${scope}`, { data: { name: 'Valorant groups', type: 'groups', status: 'upcoming', order: 1, config: { bo: 3, advanceCount: 1, groups: [{ id: 'g', teamIds: [own.id, opponent.id] }] } } })
  expect(phaseRes.ok()).toBeTruthy()
  const phase = await phaseRes.json()
  expect((await request.post(`/api/admin/fases/generate${scope}`, { data: { phaseId: phase.id } })).ok()).toBeTruthy()
  const matches = await (await request.get(`/api/admin/partidos${scope}`)).json()
  expect(matches.length).toBeGreaterThan(0)
  const match = matches[0]
  const result = await request.put(`/api/admin/partidos${scope}`, { data: { ...match, scheduledAt: '2026-10-01T18:00:00Z', result: { team1Score: 2, team2Score: 0 }, winnerId: match.team1Id, maps: [{ map: 'Ascent', team1Rounds: 13, team2Rounds: 7 }, { map: 'Haven', team1Rounds: 14, team2Rounds: 12 }] } })
  expect(result.ok()).toBeTruthy()
  expect((await request.post(`/api/admin/partidos/codes${scope}`, { data: { matchId: match.id } })).status()).toBe(422)
  expect((await request.patch(`/api/admin/equipos/${teams[0].id}/access${scope}`, { data: { enabled: false } })).status()).toBe(404)
  expect((await request.put(`/api/admin/equipos${scope}`, { data: teams[0] })).status()).toBe(404)
  await request.post('/api/admin/torneos', { data: { ...val, status: 'published' } })
  await page.goto(`/admin/equipos?tournament=${val.id}`)
  await page.getByRole('button', { name: /Repeated team name 1 jugadores/ }).click()
  await expect(page.getByRole('combobox', { name: 'Condición de Same#EUW' })).toBeVisible()
  await expect(page.getByRole('combobox', { name: /Rol principal de Same#EUW/ })).toHaveValue('Flexible')
  const access = await (await request.get(`/api/admin/equipos/${own.id}/access${scope}`)).json()
  expect((await request.post('/api/team/login', { data: { teamId: own.id, password: access.password } })).ok()).toBeTruthy()
  const portal = await (await request.get(`/api/team?tournament=${editions[0].id}`)).json()
  expect(portal.team.id).toBe(own.id)
  const change = await request.post(`/api/team/requests?tournament=${editions[0].id}`, { data: { type: 'new_player', summonerName: 'Substitute#EUW', primaryRole: 'Centinela', rosterStatus: 'substitute' } })
  expect(change.ok()).toBeTruthy()
  const changeRequest = await change.json()
  expect((await request.post(`/api/admin/solicitudes/${changeRequest.id}/approve${scope}`)).ok()).toBeTruthy()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(`/partidos${scope}`)
  await expect(page.getByRole('heading', { name: `Partidos · ${val.name}` })).toBeVisible()
  await page.goto(`/partidos/${match.id}${scope}`)
  await expect(page.getByText('Serie (mapas): 2 : 0')).toBeVisible()
  await expect(page.getByText('Ascent · Rondas: 13 : 7')).toBeVisible()
  await page.goto(`/equipos/${own.id}${scope}`)
  await expect(page.getByText('Substitute#EUW · Suplente · Centinela')).toBeVisible()
  await expect(page.getByText(/Perfil competitivo oficial/)).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Menú', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Comparar', exact: true })).toHaveCount(0)
  await page.getByRole('link', { name: 'Inicio', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`tournament=${val.id}`))
  const gameFilters = page.getByRole('navigation', { name: 'Filtrar por juego' })
  const matchCard = page.locator(`a[href^="/partidos/${match.id}?"]`)
  await expect(gameFilters.getByRole('link', { name: 'Valorant' })).toHaveAttribute('aria-current', 'page')
  await expect(page.getByRole('combobox', { name: 'Torneo' })).toHaveValue(val.id)
  await expect(matchCard).toBeVisible()
  await gameFilters.getByRole('link', { name: 'LoL' }).click()
  await expect(matchCard).toHaveCount(0)
  await gameFilters.getByRole('link', { name: 'Todos' }).click()
  await expect(page).toHaveURL(/\?game=all$/)
  await expect(matchCard).toBeVisible()
  await gameFilters.getByRole('link', { name: 'Valorant' }).click()
  await expect(page).toHaveURL(/\?game=valorant$/)
  await page.getByRole('combobox', { name: 'Torneo' }).selectOption(val.id)
  await expect(page).toHaveURL(new RegExp(`tournament=${val.id}`))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await request.post('/api/admin/torneos', { data: { ...val, status: 'archived' } })
  expect((await request.post(`/api/admin/equipos${scope}`, { data: { name: 'Blocked', players: [] } })).status()).toBe(409)
  expect((await request.post('/api/team/requests', { data: { type: 'new_player', summonerName: 'Blocked#EUW', primaryRole: 'Flexible' } })).status()).toBe(409)
  await page.goto(`/admin/fases${scope}`)
  await expect(page.getByRole('button', { name: 'Añadir fase' })).toBeDisabled()
  await expect(page.getByRole('textbox', { name: /Nombre de la fase 1/ })).toBeDisabled()
  await page.goto(`/admin/partidos${scope}`)
  await expect(page.getByRole('button', { name: 'Añadir', exact: true })).toBeDisabled()
  await page.goto('/')
  await expect(page.getByRole('link', { name: /Edition 2/ })).toHaveCount(0)
  await expect(page.getByRole('combobox', { name: 'Torneo' }).locator('option', { hasText: 'Edition 2' })).toHaveCount(0)
  await expect(page.locator(`nav[aria-label="Navegación principal"] a[href*="${val.id}"]`)).toHaveCount(0)
  expect((await (await request.get('/api/data/torneos')).json()).some((t: { id: string }) => t.id === val.id)).toBe(false)
  expect((await request.get(`/partidos/${match.id}`)).status()).toBe(404)
  expect((await request.get(`/fases${scope}`)).status()).toBe(404)
  expect((await request.get(`/api/data/fases${scope}`)).status()).toBe(404)
  expect((await request.get(`/overlay/fases/${phase.id}${scope}`)).status()).toBe(404)
  await page.goto('/admin/valorant')
  await page.getByRole('button', { name: 'Ver fixture de desarrollo' }).click()
  await expect(page.getByText('DATOS SIMULADOS · Fixture privado de desarrollo')).toBeVisible()
  await expect(page.getByText('Posición 700 · 100 RR')).toBeVisible()
})
