import path from 'path'
import { UPLOADS_DIR } from './env'

export const UPLOAD_URL_PREFIX = '/api/uploads/'

// Upload names are generated by the server. Keep this check strict as it is
// also used when resolving paths from data persisted by older versions.
const SAFE_FILENAME = /^[A-Za-z0-9][A-Za-z0-9._-]{0,254}$/
const WINDOWS_DEVICE_NAME = /^(?:con|prn|aux|nul|com[0-9]|lpt[0-9])(?:\..*)?$/i

/**
 * Resolves a filename below the uploads directory, or returns null for any
 * value that could escape it. This is intentionally based on path.resolve and
 * path.relative instead of trusting path.join's normalization.
 */
export function resolveUploadPath(filename: string): string | null {
  if (
    !SAFE_FILENAME.test(filename)
    || filename.endsWith('.')
    || filename.endsWith(' ')
    || WINDOWS_DEVICE_NAME.test(filename)
  ) return null

  const uploadsRoot = path.resolve(UPLOADS_DIR)
  const filePath = path.resolve(uploadsRoot, filename)
  const relative = path.relative(uploadsRoot, filePath)

  if (!relative || relative.startsWith('..') || path.isAbsolute(relative)) return null
  return filePath
}

export function getUploadFilename(logoPath: string): string | null {
  if (!logoPath.startsWith(UPLOAD_URL_PREFIX)) return null
  const filename = logoPath.slice(UPLOAD_URL_PREFIX.length)
  return resolveUploadPath(filename) ? filename : null
}

export function uploadUrl(filename: string): string {
  if (!resolveUploadPath(filename)) throw new Error('Nombre de archivo no válido')
  return `${UPLOAD_URL_PREFIX}${filename}`
}
